### ISSUE TITLE
ImportError: No module named pigpio

### ISSUE THREAD

**Issue by Haffwa** [calliconfused/OctoPrint-LEDmyprinterglow#1]
Hi,
I downloaded the latest OctoPrint version from http://octoprint.org/download/ and put it on my raspberry pi 3's sd card. OctoPrint is working so far (haven't received my 3D printer yet).
I don't even have LEDs connected to the pins cause they aren't here yet too.

When I startup the pi and look in OctoPrint's log files, I get the error:
`017-01-16 03:28:09,629 - octoprint.server - INFO - Starting OctoPrint 1.3.0.post1+g1014712 (master branch)
2017-01-16 03:28:09,768 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2017-01-16 03:28:11,814 - octoprint.plugin.core - ERROR - Error loading plugin led_my_printer_glow
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugin/core.py", line 669, in _import_plugin
    instance = imp.load_module(key, f, filename, description)
  File "/home/pi/.octoprint/plugins/led_my_printer_glow.py", line 7, in <module>
    import pigpio
ImportError: No module named pigpio`

All other plugins work. 
pigpiod is running as well. When I test pigpio by running python and entering `import pigpio`, I dont get any errors. Do the LEDs have to be connected that this works or did I mess something up with permissions? 
Any help, will be highly appreciated

**Comment by calliconfused** [comment]
Hi Haffwa,

Thank you very much for this issue. During the last version of RPi Jessy it seems there is a problem with the implemented libraries of pigpiod.

Did you installed them manually like in the description?

 
Next thing is that the pigpiod needs root permissions (please don’t ask me why). So please check with `sudo crontab -e` if there is the line `@reboot              /usr/local/bin/pigpiod` exists.

I hope I could help you. Feel free to contact me. Cheers! Calli

**Comment by Haffwa** [comment]
Hi!
Yes I installed it manually like in the description and `@reboot              /usr/local/bin/pigpiod` was added with `sudo crontab -e`.
I thought it might be an issue, that the octoprint image uses jessie lite.

**Comment by calliconfused** [comment]
Okay, can try point 6 of this description, please?
http://popoklopsi.github.io/RaspberryPi-LedStrip/#!/
I think there is an issue with a python library. I'm sorry that I'm not an expert ... yet.

**Comment by Haffwa** [comment]
When i try `pigs p 17 255` I don't get an error, but the LEDs haven't arrived yet, so I can't check if they would light up.

**Comment by calliconfused** [comment]
Good morning. I found one try. Please check if the python library exists:
`sudo apt-get update
sudo apt-get install pigpio python-pigpio python3-pigpio`
Here the original link:
http://abyz.co.uk/rpi/pigpio/download.html

**Comment by Haffwa** [comment]
Hi! I tried it but I still get the same error in the log-file. So I just switched to the Illuminatrix addon/plugin [https://github.com/docdawning/Illuminatrix](url)
As soon as the LED strips arrive, I might get back to this again and try to make it work.
Many thanks for your time and help!

**Comment by calliconfused** [comment]
Okay, you're welcome ;-) please keep me informed if you get the LED straps. Cheers

**Comment by Haffwa** [comment]
Will sure do, LEDs should arrive this or early next week...(hopefully ;-))

**Comment by Haffwa** [comment]
Hi!
The LED strip arrived! I hooked everything up and tried them with `pigs p 17 255`... that works! The LEDs light up in the color of the pin I use.
After that i went to ~/.octoprint/plugins and tried to download the code but I got an error.
`pi@octopi:~/.octoprint/plugins $ git clone https://github.com/calliconfused/OctoPrint-LEDmyprinterglow/blob/master/led_my_printer_glow.py
Cloning into 'led_my_printer_glow.py'...
remote: Not Found
fatal: repository 'https://github.com/calliconfused/OctoPrint-LEDmyprinterglow/blob/master/led_my_printer_glow.py/' not found`
so I downloaded with `git clone https://github.com/calliconfused/OctoPrint-LEDmyprinterglow` and moved the led_my_printer_glow.py to `~/.octoprint/plugins`.

Unfortunately that didn't help, after reboot I still get the error `2017-01-19 13:56:20,129 - octoprint.server - INFO - Goodbye!
2017-01-19 13:56:25,770 - octoprint.server - INFO - Starting OctoPrint 1.3.0.post1+g1014712 (master branch)
2017-01-19 13:56:25,910 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2017-01-19 13:56:28,028 - octoprint.plugin.core - ERROR - Error loading plugin led_my_printer_glow
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugin/core.py", line 669, in _import_plugin
    instance = imp.load_module(key, f, filename, description)
  File "/home/pi/.octoprint/plugins/led_my_printer_glow.py", line 4, in <module>
    import pigpio
ImportError: No module named pigpio
2017-01-19 13:56:28,455 - octoprint.plugin.core - INFO - Found 10 plugin(s) providing 10 mixin implementations, 7 hook handlers
2017-01-19 13:56:28,507 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2017-01-19 13:56:28,511 - octoprint.plugin.core - ERROR - Error loading plugin led_my_printer_glow
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugin/core.py", line 669, in _import_plugin
    instance = imp.load_module(key, f, filename, description)
  File "/home/pi/.octoprint/plugins/led_my_printer_glow.py", line 4, in <module>
    import pigpio
ImportError: No module named pigpio
2017-01-19 13:56:28,753 - octoprint.plugin.core - INFO - Found 10 plugin(s) providing 10 mixin implementations, 7 hook handlers`

So somehow, I still can't import pigpio in the .py file. Have no clue why, could it be a permission error?

Best regards

**Comment by calliconfused** [comment]
Good Evening! So, I installed a complete fresh new Raspian on my PrinterPi and ... same issue. Please double check it again and open `Python` and type `import pigpio`. 
In the first stage I got the _ImportError: No module named octoprint.plugin_ then type `exit()` and try to install the pigpio library directly from the Raspian:
`sudo apt-get install pigpio python-pigpio python3-pigpio`
After that I got no error.

The download was broken (ooops!). Many thanks for your hint!! I'm going to correct that.

**Comment by Haffwa** [comment]
Hi! This is how it looks like:
![image](https://cloud.githubusercontent.com/assets/17971355/22167408/6a0f6160-df66-11e6-8ffc-c959f7e60795.png)
I dont get an error in python, but the error in the log file is still existing:
`octoprint.server - INFO - Starting OctoPrint 1.3.0.post1+g1014712 (master branch)
octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
octoprint.plugin.core - ERROR - Error loading plugin led_my_printer_glow
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugin/core.py", line 669, in _import_plugin
    instance = imp.load_module(key, f, filename, description)
  File "/home/pi/.octoprint/plugins/led_my_printer_glow.py", line 4, in <module>
    import pigpio
ImportError: No module named pigpio`

Did you install a full version of Raspian / Did you build OctoPrint from source? Because I used the OctoPi Image which they provide on their website and that is based on Jessie Lite as far as I know.

**Comment by calliconfused** [comment]
Ah, OctoPrint has its own virtual environment. It seems that the module isn't available in this venv (but it makes no sense). I'm currently not at my computer to check that.
Please try `pip install pigpio` in the OctoPrint/venv/bin/pip folder. But I'm not sure if this works.

**Comment by Haffwa** [comment]
Still doesn't work
![image](https://cloud.githubusercontent.com/assets/17971355/22168211/6c49e6da-df6b-11e6-9ffa-587b17468839.png)
I don't have a venv-folder.
But I don't want to waste your time, I hooked up my Uno to the Pi and got the "Illuminatrix" plugin, which is working quite well (its just a little bit slow, when it comes to changing colors).
